### ISSUE TITLE
Complete from all open buffers option

### ISSUE THREAD

**Issue by dwoznicki** [hrsh7th/cmp-buffer#1]
The following configuration works fine for me, but it would probably be nicer (and a bit safer) if there was a boolean option that could be set to get the same behavior (something like `useAllBuffers = true` as mentioned in a previous thread) without overriding a function.

```lua
require'cmp'.setup {
  sources = {
    {
      name = 'buffer',
      opts = {
        get_bufnrs = function()
          return vim.api.nvim_list_bufs()
        end
      }
    }
  }
}
```

Alternatively, we could note the `vim.api.nvim_list_bufs()` solution as a recipe in the README.

Note that I performance seemed fine with ~40 buffers open and ~30,000 total words across all buffers.

Related: hrsh7th/nvim-compe#147, hrsh7th/nvim-compe#393

**Comment by hrsh7th** [comment]
I will add a note to README.md about `vim.api.nvim_list_bufs` Thank you.

**Comment by hrsh7th** [comment]
@dwoznicki I've added two pre-defined recipes to README.md. Thank you~!

**Comment by lowski** [comment]
Sorry for jumping in but I wanted thank @dwoznicki for the snippet in the first post.

It wasn't clear for me that I need to pass `get_buffnrs` under `option` keyword (`opts` is deprecated). From the README I got an impression it needs to go directly after the name like this:

```
require'cmp'.setup {
  sources = {
    {
      name = 'buffer',
      get_bufnrs = function()
        return vim.api.nvim_list_bufs()
      end
    }
  }
}
```

**Comment by jhhuisman** [comment]
Thanks @lcmen and @dwoznicki.
@hrsh7th please add the context/example given by @lcmen to the readme. 
I also couldn't figure out where to add the function myself.

**Comment by hrsh7th** [comment]
I've updatedthe README.md :)

**Comment by youssef-lr** [comment]
For anyone reading this from google and to save you a trip to `:h cmp-buffer`, this is the correct config:

```
{
  name = 'buffer',
  option = {
    get_bufnrs = function()
      return vim.api.nvim_list_bufs()
    end
  }
},
```
