### ISSUE TITLE
Diacritic characters are ignored

### ISSUE THREAD

**Issue by xeluxee** [hrsh7th/cmp-buffer#11]
Same as https://github.com/hrsh7th/nvim-compe/issues/541#issue-977420645

**Comment by dmitmel** [comment]
Try setting the `keyword_pattern` option to `[[\k\+]]`.

**Comment by hrsh7th** [comment]
See https://github.com/hrsh7th/cmp-buffer/issues/4

If you think it's unnoticavle, please create PR.

**Comment by xeluxee** [comment]
> Try setting the `keyword_pattern` option to `[[\k\+]]`.

It works thanks

**Comment by amiroslaw** [comment]
I think this problem come back. I've installed cmp today I have the same problem. Do I  also need add something to cmp.setup.completion?

**Comment by dmitmel** [comment]
Please provide an example so that we can reproduce the bug

**Comment by amiroslaw** [comment]
Sorry for delay. I had to clean my config cos I've just finished migration to lua config. 
<details><summary>init.lua</summary>

```lua
vim.o.completeopt = 'menu,menuone,noselect'

local cmp = require 'cmp'
cmp.setup {
	snippet = {
		expand = function(args)
			vim.fn['UltiSnips#Anon'](args.body)
		end,
	},
	mapping = {
		['<CR>'] = cmp.mapping(cmp.mapping.confirm { select = true }, { 'i', 'c' }),
		['<C-Space>'] = cmp.mapping(cmp.mapping.confirm { select = true }, { 'i', 'c' }),
		['<C-j>'] = cmp.mapping(cmp.mapping.select_next_item { behavior = cmp.SelectBehavior.Insert }, { 'i', 'c' }),
		['<C-k>'] = cmp.mapping(cmp.mapping.select_prev_item { behavior = cmp.SelectBehavior.Insert }, { 'i', 'c' }),
		['<C-w>'] = cmp.mapping { i = cmp.mapping.abort(), c = cmp.mapping.close() }, 
		['<C-S-Space>'] = cmp.mapping(cmp.mapping.complete(), { 'i', 'c' }), 
		['<C-y>'] = cmp.config.disable, 
	},
	sources = {
		{ name = 'buffer', keyword_length = 2, keyword_pattern = [[\k\+]] },
		{ name = 'nvim_lua' },
		{ name = 'ultisnips' },
		{ name = 'path' },
		{ name = 'calc' },
	},
}

-- CMD mode - if you are in that mode and put / or : ' (if you enabled `native_menu`, this won't work anymore).
cmp.setup.cmdline('/', {
	sources = {
		{ name = 'buffer' },
	},
})
cmp.setup.cmdline(':', {
	sources = {
		{ name = 'cmdline_history', keyword_length = 3 },
		{ name = 'path' },
	},
})
```
</details>

<details><summary>plugins.lua</summary>

```lua
use {
	'hrsh7th/nvim-cmp',
	requires = {
		{ 'hrsh7th/nvim-cmp' },
		{ 'hrsh7th/cmp-buffer' },
		{ 'hrsh7th/cmp-path' },
		{ 'hrsh7th/cmp-calc' },
		{ 'dmitmel/cmp-cmdline-history' },
		{ 'quangnguyen30192/cmp-nvim-ultisnips' },
		{ 'hrsh7th/cmp-nvim-lua' }, -- vim.api
		{ 'hrsh7th/cmp-nvim-lsp' },
	},
}

```
</details>

I don't know how to proper debug nvim. If you like you can check out my dotfiles on [github](https://github.com/amiroslaw/dotfiles/tree/master/common/nvim/.config/nvim)

**Comment by dmitmel** [comment]
@amiroslaw Well, the config looks fine. Can you also give a file with which the problem can be reproduced?

**Comment by amiroslaw** [comment]
I've also checked out other languages and I have the same problem with different diacritics. The problem appears in any filetype.

##### Polish

księżyc głównie przyszłość trzydzieści rozdział szczególnie odpowiedź ostrożnie większość dwadzieścia dziesięć światło szczęście rzeczywiście przecież

##### Greek

monotonikó sýstīma grafīs


##### Portugues

Sinônimos (inglês) linguística diacrítico em inglês

**Comment by dmitmel** [comment]
That's really weird. For me it works fine (I think):

![image](https://user-images.githubusercontent.com/15367354/144366691-75ebc897-0697-4279-8478-f54233d5ad4e.png)

**Comment by amiroslaw** [comment]
Yes I want to achieve this result. Unfortunately those patterns didn't work either. 

I think that default keyword_pattern doesn't replace by user's one. When I replaced it in the `source.lua` the problem disappeared. I have the newest version.

```lua
local defaults = {
  keyword_length = 3,
	keyword_pattern = [[\k\+]], 
  -- keyword_pattern = [[\%(-\?\d\+\%(\.\d\+\)\?\|\h\w*\%([\-]\w*\)*\)]],
  get_bufnrs = function()
    return { vim.api.nvim_get_current_buf() }
  end,
}
```

**Comment by dmitmel** [comment]
Oh I forgot, you have to specify the `keyword_pattern` like this:
```lua
cmp.setup({
  sources = {
    {
      name = 'buffer',
      option = { keyword_pattern = [[\k\+]] },
    },
  },
})
```
instead of
```lua
cmp.setup({
  sources = {
    {
      name = 'buffer',
      keyword_pattern = [[\k\+]],
    },
  },
})
```
