### ISSUE TITLE
Error about invalid buffer id

### ISSUE THREAD

**Issue by AgentCosmic** [hrsh7th/cmp-buffer#14]
I sometimes get this error out of the blue. And I can't make the error go away because it keeps popping up after I close it. I don't know how to reproduce it yet.

![image](https://user-images.githubusercontent.com/1035714/136514676-b1ece8ae-67c7-4efd-96b4-d271ac6fed7c.png)

**Comment by sQVe** [comment]
@hrsh7th I'm now getting this consistently after running `PackerSync` or running `enew` via *dashboard-nvim*. It continuously spams this error so the only solution is to exit vim and open a new one.

I've tried removing loading `cmp` async but that made no difference. This is my current `cmp` setup:


```lua
    -- Completion.
    use({
        'hrsh7th/nvim-cmp', -- Completion engine.
        config = require('plugins.completion.cmp'),
        event = {'CmdlineEnter', 'InsertEnter'},
        requires = {'onsails/lspkind-nvim'},
    })
    use({'hrsh7th/cmp-buffer', after = 'nvim-cmp'}) -- Buffer completion.
    use({'hrsh7th/cmp-cmdline', after = 'nvim-cmp'}) -- Command completion.
    use({'hrsh7th/cmp-nvim-lsp', after = 'nvim-cmp'}) -- LSP completion.
    use({'hrsh7th/cmp-nvim-lua', after = 'nvim-cmp'}) -- API completion.
    use({'hrsh7th/cmp-path', after = 'nvim-cmp'}) -- Path completion.
    use({'hrsh7th/cmp-vsnip', after = 'nvim-cmp'}) -- VSnip completion.
    use({
        'hrsh7th/vim-vsnip', -- Snippet support.
        after = 'nvim-cmp',
        setup = require('plugins.completion.vsnip'),
    })

```
