### ISSUE TITLE
Weird placement in completion menu 

### ISSUE THREAD

**Issue by aditya-K2** [hrsh7th/cmp-buffer#19]
When I enable buffer in source the placement of suggestions is very weird in non-native menu. 

![Nov06(Sat)10:5659PM](https://user-images.githubusercontent.com/51816057/140618549-c5a55ccb-8009-44dd-972c-2dc5bfe8f12f.png)

**Comment by hrsh7th** [comment]
I can't understand.

**Comment by aditya-K2** [comment]
the suggestions from buffer and the lsp suggestions are placed differently

**Comment by aditya-K2** [comment]
as you can see in the image some suggestions are placed correctly some are not

**Comment by hrsh7th** [comment]
Please provide the minimal reproducible configuration.
And menu appearance is nvim-cmp's core area, please re-send issue to nvim-cmp itself.

**Comment by aditya-K2** [comment]
I think this is an issue with clangd itself.
