### ISSUE TITLE
Is it possible to sort by "distance"

### ISSUE THREAD

**Issue by kuon** [hrsh7th/cmp-buffer#25]
There is a feature I'd really like, but I do not know how hard it would be.

I use buffer completion and it works very well, but I'd love to have the proposition sorted by distance.

For example, if I have this file:

```txt

hola
hoy
hey


h
```

when I type the `h` on the last line, I'd like the proposition to be:

```txt

hey, hoy, hola (current file, closest to m line)
.... (other files)

```

I attached an image with the current results I get.

![20211112_01h12m46s_grim](https://user-images.githubusercontent.com/160200/141386942-aa425433-7e7f-4f52-9b91-5382a3ec4a46.png)

**Comment by dmitmel** [comment]
Ref: https://github.com/hrsh7th/nvim-cmp/issues/183

I'm on it.

**Comment by kuon** [comment]
This is great. I keep this open in the meantime, to provide feedback for this specific feature in this context (buffers).
