### ISSUE TITLE
Error keyboard interrupt

### ISSUE THREAD

**Issue by tien0409** [hrsh7th/cmp-buffer#30]
whenever I go newline with keyboard 'o' then go up a new line with 'shift-o' the result is as shown below
![image](https://user-images.githubusercontent.com/53030937/142882852-19d986af-e292-4233-aed7-269c02d72378.png)

**Comment by dmitmel** [comment]
Can't reproduce. Could you please provide a minimal config and a file with which the error occurs?

**Comment by tien0409** [comment]
> Can't reproduce. Could you please provide a minimal config and a file with which the error occurs?

**My config**
g.completeopt = 'menu,menuone,noselect,noinsert'

local has_words_before = function()
  local line, col = unpack(vim.api.nvim_win_get_cursor(0))
  return col ~= 0 and vim.api.nvim_buf_get_lines(0, line - 1, line, true)[1]:sub(col, col):match("%s") == nil
end

local feedkey = function(key, mode)
  vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes(key, true, true, true), mode, true)
end

local cmp = require('cmp')
local cmp_buffer = require('cmp_buffer')
local lspkind = require('lspkind')

local source_mapping = {
	buffer = "[Buffer]",
	nvim_lsp = "[LSP]",
	nvim_lua = "[Lua]",
	cmp_tabnine = "[TN]",
	path = "[Path]",
}

cmp.setup {
  formatting = {
    format = function (entry, vim_item)
      vim_item.kind = lspkind.presets.default[vim_item.kind]
			local menu = source_mapping[entry.source.name]
			if entry.source.name == 'cmp_tabnine' then
				if entry.completion_item.data ~= nil and entry.completion_item.data.detail ~= nil then
					menu = entry.completion_item.data.detail .. ' ' .. menu
				end
				vim_item.kind = ''
			end
			vim_item.menu = menu
			return vim_item
    end
  },
  snippet = {
    expand = function(args)
      vim.fn["vsnip#anonymous"](args.body) -- For `vsnip` users.
    end
  },
  mapping = {
    ["<Tab>"] = cmp.mapping(function(fallback)
      if cmp.visible() then
        cmp.select_next_item()
      elseif vim.fn["vsnip#available"](1) == 1 then
        feedkey("<Plug>(vsnip-expand-or-jump)", "")
      elseif has_words_before() then
        cmp.complete()
      else
        fallback() -- The fallback function sends a already mapped key. In this case, it's probably `<Tab>`.
      end
    end, { "i", "s" }),

    ["<S-Tab>"] = cmp.mapping(function()
      if cmp.visible() then
        cmp.select_prev_item()
      elseif vim.fn["vsnip#jumpable"](-1) == 1 then
        feedkey("<Plug>(vsnip-jump-prev)", "")
      end
    end, { "i", "s" }),

    ['<C-p>'] = cmp.mapping.select_prev_item(),
    ['<C-n>'] = cmp.mapping.select_next_item(),
    ['<C-d>'] = cmp.mapping.scroll_docs(-4),
    ['<C-f>'] = cmp.mapping.scroll_docs(4),
    ['<C-Space>'] = cmp.mapping.complete(),
    ['<C-e>'] = cmp.mapping.close(),
    ['<CR>'] = cmp.mapping.confirm({
      behavior = cmp.ConfirmBehavior.Insert,
      select = true,
    }),
    ['<C-j>'] = cmp.mapping.confirm({
      behavior = cmp.ConfirmBehavior.Insert,
      select = true,
    })
  },
  sources = cmp.config.sources({
    { name = 'nvim_lsp' },
    { name = 'path' },
    { name = 'vsnip' },
    { name = 'nvim_lua' },
    {
      name = 'buffer',
      opts = {
        get_bufnrs = function()
          local bufs = {}
          for _, win in ipairs(vim.api.nvim_list_wins()) do
            bufs[vim.api.nvim_win_get_buf(win)] = true
          end
          return vim.tbl_keys(bufs)
        end
      }
    },
    { name = 'cmp_tabnine'}
  }, {

  }),
}

cmp.setup.cmdline('/', {
  sources = {
    { name = 'buffer' }
  }
})

-- Use cmdline & path source for ':' (if you enabled `native_menu`, this won't work anymore).
cmp.setup.cmdline(':', {
  sources = cmp.config.sources({
    { name = 'path' }
  }, {
    { name = 'cmdline' }
  })
})

cmd [[
  imap <expr> <Tab>   vsnip#jumpable(1)   ? '<Plug>(vsnip-jump-next)'      : '<Tab>'
  smap <expr> <Tab>   vsnip#jumpable(1)   ? '<Plug>(vsnip-jump-next)'      : '<Tab>'
  imap <expr> <S-Tab> vsnip#jumpable(-1)  ? '<Plug>(vsnip-jump-prev)'      : '<S-Tab>'
  smap <expr> <S-Tab> vsnip#jumpable(-1)  ? '<Plug>(vsnip-jump-prev)'      : '<S-Tab>'
]]

**File error**
all files, even simple ones like the following 
![image](https://user-images.githubusercontent.com/53030937/142980600-8e0ee752-2040-42fb-a72d-1d2a05897234.png)

**Comment by dmitmel** [comment]
Can't reproduce with your config. I don't get it. Can you maybe record a video with a program that shows keypresses? [screenkey](https://github.com/wavexx/screenkey) for Linux and [keycastr](https://github.com/keycastr/keycastr) for macOS.

**Comment by dmitmel** [comment]
Also: are you using neovim nightly? And can you please update nvim-cmp and cmp-buffer to the latest commits, just in case?

**Comment by tien0409** [comment]
![error](https://user-images.githubusercontent.com/53030937/143003316-549f4e07-0fdf-4c30-adf1-65472ecd5058.gif)
sorry I don't know how to use these tools. I have updated to the latest version of nvim-cmp, my version neovim:  NVIM v0.6.0-dev. My os ubuntu-20.04.3

**Comment by dmitmel** [comment]
https://user-images.githubusercontent.com/15367354/143017546-355d9cda-cb76-43d5-8bf8-161b468b2eeb.mp4

**Comment by dmitmel** [comment]
Can you please check if commit d1ca295ce584ec80763a6dc043080874b57ccffc triggers the error?

**Comment by dmitmel** [comment]
Nevermind, I have FINALLY understood the issue. You were pressing Ctrl+C and not Esc to exit the Insert mode, and it was somehow interfering with just this plugin. I'll try to fix it.

**Comment by tien0409** [comment]
> Nevermind, I have FINALLY understood the issue. You were pressing Ctrl+C and not Esc to exit the Insert mode, and it was somehow interfering with just this plugin. I'll try to fix it.
Yes, tried with ESC and not error

**Comment by dmitmel** [comment]
Alright, I believe this is a bug in Neovim itself, I'll try creating a minimal repro and open a ticket there. As a workaround, you can use this:

```vim
inoremap <C-c> <Esc>
```

**Comment by tien0409** [comment]
> Alright, I believe this is a bug in Neovim itself, I'll try creating a minimal repro and open a ticket there. As a workaround, you can use this:
> 
> ```viml
> inoremap <C-c> <Esc>
> ```

tks

**Comment by dmitmel** [comment]
Ref: https://github.com/neovim/neovim/issues/16416

**Comment by callms** [comment]
For those using the `inoremap` trick and find out their cursor move after hitting `^C`, use the following:

```vim
inoremap <C-c> <Esc>`^
```

If you're using Lua:

```lua
vim.cmd([[ inoremap <C-c> <Esc>\`^ ]])
```
