### ISSUE TITLE
buffer.lua:317: bad argument #1 to ipairs (table expected, got userdata)

### ISSUE THREAD

**Issue by rhcher** [hrsh7th/cmp-buffer#33]
![image](https://user-images.githubusercontent.com/50723480/146353954-c88aafc7-3616-4c13-aea8-c086228dbb98.png)

neovim version :NVIM v0.7.0-dev+727-g326e74571b

But I can't reproduce the bug consistently...

**Comment by dmitmel** [comment]
@rhcher Did you find a solution?

**Comment by rhcher** [comment]
> @rhcher Did you find a solution or a cause?

No, but I only encountered this problem twice, and I couldn't reproduce the bug after that. So I guess it's just some coincidence.
