### ISSUE TITLE
when using cmp-buffer, <C-A> act weirdly.

### ISSUE THREAD

**Issue by gen740** [hrsh7th/cmp-buffer#34]
### neovim version
- NVIM v0.6.0
- use packer.nvim, nvim-cmp and amp-buffer

###  how to reproduce
The minimum config to reproduce this bug is following.
```
require("packer").startup({
	function(use)
		use({
			"wbthomason/packer.nvim",
		})
		use({
			"hrsh7th/nvim-cmp",
			requires = {
				{
					"hrsh7th/cmp-buffer",
				},
			},
			config = function ()
				require"cmp".setup({
					sources = {
						{ name = "nvim_lsp" },
						{ name = "buffer"},
					},
				})
			end,
		})
	end,

})
```
- at first type `text 0`
- and then, type `<C-a>`

### expect behavior
type `text 0` and press `<C-a>` will return text `text 1`

### actual behavior
`<C-a>` return `text1 `

**Comment by dmitmel** [comment]
Thanks for a report! This is actually a bug in Neovim (I've opened a ticket on their repo, ref: https://github.com/neovim/neovim/issues/16729), but I'll introduce a workaround for it in this plugin.
