### ISSUE TITLE
Support non-ascii words

### ISSUE THREAD

**Issue by igorlfs** [hrsh7th/cmp-buffer#36]
I'm sorry if this is a misconfiguration on my end, but I couldn't get any suggestions with words containing characters like `ç` or `ã`.

**Comment by cands** [comment]
I experience the same issue (e.g. with characters å, ä, ö).

**Comment by igorlfs** [comment]
Setting 
```
option = {
    keyword_pattern = [[\k\+]],
}
```
Fixes the issue. Is there any reason for this not to be the default?

**Comment by mawkler** [comment]
Thanks, that solved the issue for me as well! I also wonder why this isn't the default 🤔
