### ISSUE TITLE
Question: How to config keyword_pattern for recognizing  `java/lang/Object;` word? 

### ISSUE THREAD

**Issue by tomasky** [hrsh7th/cmp-buffer#38]
How to config keyword_pattern for recognizing  `java/lang/Object;` word?

**Comment by hrsh7th** [comment]
I can't understand. Sorry. Please explain it more.

**Comment by tomasky** [comment]
I want  the buffer to recognize some words like `java/lang/Object;`

**Comment by hrsh7th** [comment]
Did you see this docs https://github.com/hrsh7th/cmp-buffer#keyword_pattern-type-string ?

**Comment by tomasky** [comment]
Yes ,  like this :
```lua
cmp.setup({
  sources = {
    {
      name = 'buffer',
      -- Correct:
      option = {
        keyword_pattern = [[\k\+]],
      }
    },
  },
})
```

**Comment by tomasky** [comment]
Thanks , need  nvim  set `iskeyword` ,now it works fine.
