### ISSUE TITLE
use 'iskeyword' option in (or, instead of) keyword_pattern

### ISSUE THREAD

**Issue by davidsierradz** [hrsh7th/cmp-buffer#4]
Hi! I think `iskeyword` serves a similar purpose (`w` motion for example)

**Comment by hrsh7th** [comment]
You can change keyword_pattern. Is,it enough to you?

**Comment by davidsierradz** [comment]
I guess so. I'm trying, but I must confess my regex knowledge is not very advanced.

My use-case is that I would like to add all valid clojure characters ([clojure.vim](https://github.com/clojure-vim/clojure.vim/blob/e3994c6ad59df6f9a0e5400c4c720194b9848d53/ftplugin/clojure.vim#L20)) so I can complete words like: `foo->bar` or `baz-quux?`.

For example, if I write `fo` I would like to get `foo->bar` in the menu, right now I only get `foo`. The same for `ba`, I would like to get `baz-quux?` only getting `baz-quux`.

I think is mostly a matter of consistency I guess. Maybe I want this special characters in clojure buffers but not javascript ones (thats why `iskeyword` is a buffer setting).

What do you think?

**Comment by hrsh7th** [comment]
Hm... I think it should be decided carefully.
At least, I don't prefer to use `iskeyword` by default.

```
cmp.setup {
  ...
  sources = {
    {
      name = 'buffer',
      opts = {
        keyword_pattern = [[\%(\w\+\|->?\)?\?]]
      }
  }
  ...
}
```

I think your expected behavior can realize the above config. Hm...

**Comment by davidsierradz** [comment]
Coming back to confirm that `keyword_pattern = [[\k\+]]` works.

Thank you!
