### ISSUE TITLE
Deal with special characters like German umlaut etc.

### ISSUE THREAD

**Issue by jamilraichouni** [hrsh7th/cmp-buffer#43]
Hi!

Really like your completion plugins a lot, thanks for sharing your great results with the community!

I just identified that the buffer source cannot deal with special (for Germans not so special) characters.
The `cmp-nvim-lsp` source is not having that issue.

It is quite simple to demonstrate that with some screenshots:

<img width="430" alt="Screenshot 2022-04-15 at 10 57 21" src="https://user-images.githubusercontent.com/45113557/163551314-f5ae7b0a-2f54-486f-b93b-9d889e16c4ff.png">

Background: [https://en.wikipedia.org/wiki/%C3%9C](https://en.wikipedia.org/wiki/%C3%9C)

<img width="336" alt="Screenshot 2022-04-15 at 10 58 27" src="https://user-images.githubusercontent.com/45113557/163551369-0bb5e86c-de69-4387-9906-e6821fe03dbd.png">

Background: [https://en.wikipedia.org/wiki/%C3%9F](https://en.wikipedia.org/wiki/%C3%9F)

Here, `cmp-nvim-lsp` handles the character `ß` correctly and `cmp-buffer` doesn't:

<img width="1056" alt="Screenshot 2022-04-15 at 11 02 36" src="https://user-images.githubusercontent.com/45113557/163551513-8edc34fa-5479-43b9-94b5-8ba60e6e8bfc.png">

Here, `cmp-nvim-lsp` handles the character `Ä` correctly and `cmp-buffer` doesn't:

<img width="750" alt="Screenshot 2022-04-15 at 11 12 24" src="https://user-images.githubusercontent.com/45113557/163551986-18a2e7b9-efcd-49bc-af80-0495959d0797.png">

All best and greeting from Berlin,
Jamil

**Comment by ten3roberts** [comment]
I am also having this problem using Swedish åäö, which are not recognised as a part of the world.

**Comment by tomtomjhj** [comment]
Try
```
...
{ name = 'buffer',
  option = {
    keyword_pattern = [[\K\k*]],
  }
},
...
```

**Comment by jamilraichouni** [comment]
That solves the issue, thanks!
