### ISSUE TITLE
recipe to pick all buffers to complete doesn't work

### ISSUE THREAD

**Issue by timsofteng** [hrsh7th/cmp-buffer#45]
Hello. The recipe to pick all buffers to completion results doesnt work for me.

`nvim 0.7`

Btw can we get rid of this code in user's config
```
                get_bufnrs = function()
                  local bufs = {}
                  for _, win in ipairs(vim.api.nvim_list_wins()) do
                    bufs[vim.api.nvim_win_get_buf(win)] = true
                  end
                  return vim.tbl_keys(bufs)
                end
```
and change it to somehting like:
```
                get_bufnrs = "allVisibleBuffers"
```
?

**Comment by hugosxm** [comment]
hi, same here, neovim 0.7 too !

**Comment by timsofteng** [comment]
> @timsofteng if you want to complete from all buffers (visible and non-visible) then use:
> 
> ```lua
> get_bufnrs = function()
>   return vim.api.nvim_list_bufs()
> end
> ```

I want complete for visible buffers only.

**Comment by hugosxm** [comment]
> @timsofteng if you want to complete from all buffers (visible and non-visible) then use:
> 
> ```lua
> get_bufnrs = function()
>   return vim.api.nvim_list_bufs()
> end
> ```

In my case this does not working, here is my full setup call : 
`cmp.setup({
    -- view = {
    --     entries = "native"
    -- },
    snippet = {
    -- REQUIRED - you must specify a snippet engine
    expand = function(args)
    -- vim.fn["vsnip#anonymous"](args.body) -- For `vsnip` users.
    require('luasnip').lsp_expand(args.body) -- For `luasnip` users.
    -- require('snippy').expand_snippet(args.body) -- For `snippy` users.
    -- vim.fn["UltiSnips#Anon"](args.body) -- For `ultisnips` users.
      end,
    },

    formatting = {
        format = function(entry, vim_item)
            -- Kind icons
            vim_item.kind = string.format('%s %s', kind_icons[vim_item.kind], vim_item.kind) -- This concatonates the icons with the name of the item kind
            -- Source
            vim_item.menu = ({
                buffer = "[Buffer]",
                nvim_lsp = "[LSP]",
                luasnip = "[LuaSnip]",
                nvim_lua = "[Lua]",
                latex_symbols = "[LaTeX]",
                path = "[Path]",
            })[entry.source.name]
            return vim_item
        end
    },

    window = {
        completion = cmp.config.window.bordered(),
        documentation = cmp.config.window.bordered(),
    },
    experimental = {
        ghost_text = true,
        -- native_menu = true,
    },
    mapping = cmp.mapping.preset.insert({
        -- ['<RIGHT>'] = cmp.mapping.select_next_item(),
        -- ['<LEFT>'] = cmp.mapping.select_prev_item(),
        ['<C-b>'] = cmp.mapping.scroll_docs(-4),
        ['<C-f>'] = cmp.mapping.scroll_docs(4),
        ['<C-Space>'] = cmp.mapping.complete(),
        ['<C-e>'] = cmp.mapping.abort(),
        ['<CR>'] = cmp.mapping.confirm({ select = true }), -- Accept currently selected item. Set `select` to `false` to only confirm explicitly selected items.
          ['<Tab>'] = function(fallback)
      if cmp.visible() then
        cmp.select_next_item()
      elseif luasnip.expand_or_jumpable() then
        luasnip.expand_or_jump()
      else
        fallback()
      end
    end,
    ['<S-Tab>'] = function(fallback)
      if cmp.visible() then
        cmp.select_prev_item()
      elseif luasnip.jumpable(-1) then
        luasnip.jump(-1)
      else
        fallback()
      end
    end,
    }),
    sources = cmp.config.sources({
    -- sources = {
        { name = 'nvim_lsp' },
        -- { name = 'vsnip' }, -- For vsnip users.
        { name = 'luasnip' }, -- For luasnip users.
        -- { name = 'ultisnips' }, -- For ultisnips users.
        -- { name = 'snippy' }, -- For snippy users.
        {
            name = 'buffer',
            keyword_length = 5,
            get_bufnrs = function()
                return vim.api.nvim_list_bufs()
            end,
        },
        { name = 'path' },
        { name = 'nvim_lua' },
    })
})`

**Comment by gegoune** [comment]
@timsofteng This is pretty bad issue. By not providing any details you are asking maintainer to debug it for you.
What's the minimal reproduction? What does 'does not work' mean? What do you expect to happen? What's happening instead?

I can tell you one thing - it works.

<img width="1120" alt="here" src="https://user-images.githubusercontent.com/69750637/165844640-3cc29cb6-569d-44dc-85a5-5c3f8d688f7b.png">

**Comment by gegoune** [comment]
Do compare your config with documentation, you have misplaced that function.
