### ISSUE TITLE
include scandinavian letters

### ISSUE THREAD

**Issue by seblj** [hrsh7th/cmp-buffer#5]
I am not able to get buffer completion on letters like æ, ø and å. I see that I can override the keyword_pattern, but I can't make sense of how to alter it to get those letters included. If you could either update the default to include those letters as well, or point me in the right direction to get this working, I would really appreciate it! Thank you!

**Comment by hrsh7th** [comment]
I think duplicate #4.

I think this issue can be solved by the following config.

```lua
cmp.setup {
  ...
  sources = {
    {
      name = 'buffer',
      opts = {
        keyword_pattern = [[\k\+]]
      }
    }
  }
```
  ...
}

**Comment by seblj** [comment]
that seems to work, thank you!!

**Comment by seblj** [comment]
I was a bit too fast there. It works, but it adds another suggestion here which I think should not be there? Shouldn't it just be `lærer` and not `lær` in the completion menu?

<img width="204" alt="image" src="https://user-images.githubusercontent.com/5160701/130671241-ab8882ce-635e-46bd-8e92-2d42b124af5b.png">

**Comment by hrsh7th** [comment]
Hm... It seems a bug to me. Because cmp-buffer will remove current keyword from candidates. See https://github.com/hrsh7th/cmp-buffer/blob/main/lua/cmp_buffer/init.lua#L36

I think it should be separated issue.

**Comment by seblj** [comment]
Oh, if I change the keyword_pattern in `completion` in nvim-cmp config to the same as you sent, as well as having it in the opts as you sent, this issue seems to go away!

**Comment by hrsh7th** [comment]
Thank you very much. I understand what's going on.

I think it should be improved by nvim-cmp iteself.

**Comment by hrsh7th** [comment]
@seblj I've improved it. You can omit the nvim-cmp's `completion.keyword_pattern` coniguration.

**Comment by languitar** [comment]
This looks still broken to me with German umlauts

![image](https://user-images.githubusercontent.com/1336287/131392113-cf1f6da3-06e5-4bf0-a946-5d1cc00b40d8.png)

git pull from today, no configuration passend to cmp-buffer

**Comment by hrsh7th** [comment]
See https://github.com/hrsh7th/cmp-buffer/issues/5#issuecomment-904877359

**Comment by languitar** [comment]
Ah, i thougjt your last comment here indicated that this was generally fixed. Any objection to making the proposed expression the default?

**Comment by hrsh7th** [comment]
I think we should focus general programming (It is ascii characters).

However, I know the user hope to support it. So  I provided a configuration option.

**Comment by languitar** [comment]
I think the buffer source is especially helpful for writing prose such as in comments or markdown files, where LSPs don't help at all. There, special characters are pretty common for any language apart from English. But also for programming, splitting on actual word character is strange. Kotlin, for instance, has Unicode support and method names are allowed to contain close to anything.

**Comment by hrsh7th** [comment]
I think the multibyte characters aren't easy to handle.

For example, In chinese/japanese, the code comments will be written in all multibyte characters.

```
/**
 * この関数は、変数 a と変数 b を受け取り、それらを加算した値を返します。
 */
export function sum(a, b) {
  return a + b;
}
```

I don't want to suggest any multibyte characters in this case.

**Comment by languitar** [comment]
Do you think that handling them in the completion popup is a problem? Or what will be hard to handle?

**Comment by hrsh7th** [comment]
For example, I can't understand why `と変数` was suggested in this case.

https://user-images.githubusercontent.com/629908/131467782-3a14bc46-06d5-4046-9d54-efce7740b503.mp4

**Comment by languitar** [comment]
Alright, I'll live with the custom configuration. Maybe some hint on the Readme that the pattern doesn't include words with special characters could help.
